org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.newDsl=false
android.experimental.privacysandbox.sdk.enable=false
android.defaults.buildfeatures.buildconfig=true
kotlin.daemon.jvmargs=-Xmx2G
kotlin.jvm.target.validation.mode=warning
