// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return android; // Using android options as a fallback for desktop if needed
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7FVrw4F7nRgn9EZiXBG5hpnque4Hln7A',
    appId: '1:498676147966:web:988edcd75e7dc10b8d27af', // Placeholder
    messagingSenderId: '498676147966',
    projectId: 'nest-d9a47',
    authDomain: 'nest-d9a47.firebaseapp.com',
    storageBucket: 'nest-d9a47.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FVrw4F7nRgn9EZiXBG5hpnque4Hln7A',
    appId: '1:498676147966:android:988edcd75e7dc10b8d27af',
    messagingSenderId: '498676147966',
    projectId: 'nest-d9a47',
    storageBucket: 'nest-d9a47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7JQX69R1hnt2Rd6Dvd1yM57nmmxLNlc',
    appId: '1:498676147966:ios:f9847df2bbf0a0da8d27af',
    messagingSenderId: '498676147966',
    projectId: 'nest-d9a47',
    databaseURL: 'https://nest-d9a47-default-rtdb.firebaseio.com',
    storageBucket: 'nest-d9a47.firebasestorage.app',
    androidClientId: '498676147966-6u8836p7812bqg510lukookpi96cmc5j.apps.googleusercontent.com',
    iosClientId: '498676147966-7mm599neqc8g4uulbh7hvr59rhsfbr04.apps.googleusercontent.com',
    iosBundleId: 'com.pixelfox.agenda',
  );
}
